name: Clean up season

on:
  repository_dispatch:
    types: [trigger-cleanup]
  workflow_dispatch:
  #push:
  #  branches:
  #    - main  # Run on pushes to the main branch

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::sf
            any::geojsonio
            any::smoothr
            any::dplyr
            any::parallel
            any::data.table
      
      #Added to try caching to save time.      
      - name: Cache R packages
        uses: actions/cache@v4 #changed from 2>4 because 2 is being phased out.
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run smoothr on day timeframes and compress season
        #run: Rscript -e 'source("250130-FixSeason.R")' #run all four timeframes
        #run: Rscript -e 'source("250131-CleanPolygons.R")' #add smoothr
        run: Rscript -e 'source("250201-CleanPolygons.R")' #also remove overlapping bits
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -m "Latest data: $(date)" || exit 0
          git push 
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions

      - name: Trigger push to Google Cloud
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-push-to-gcp
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'