name: Process with Mapshaper

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main  # Run on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Or macos-latest if you prefer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set the version of Node.js

      - name: Install Mapshaper
        run: npm install -g mapshaper  # Install Mapshaper globally

      - name: Run Mapshaper Command
        run: mapshaper outputs/input.json -o precision=0.1 outputs/snowfall.json  # Run your Mapshaper command directly

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -m "Latest data: $(date)" || exit 0
          git push 
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
