name: push_to_gcp

on:
  #schedule:
  #  - cron: '0 */6 * * *' # Run every six hours
  workflow_dispatch:
#  push:
#    branches: main

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install googleCloudStorageR
        run: Rscript -e 'install.packages("googleCloudStorageR", dependencies = TRUE, repos = "http://cran.r-project.org")'


      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Save GCP credentials to temp file
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > gcp-key.json

      - name: Verify GCP credentials file
        run: |
          if [ -f gcp-key.json ]; then
            echo "GCP credentials file created successfully."
            echo "First few lines of the file:"
            head -n 5 gcp-key.json
          else
            echo "GCP credentials file not found!"
            exit 1
          fi
          
      - name: Test googleCloudStorageR
        run: |
          echo "library(googleCloudStorageR)" > test.R
          Rscript test.R
          

      - name: Run R script
        env:
          GCS_AUTH_FILE: gcp-key.json
        run: Rscript -e 'source("251128-PushToGCP.R")'