name: push_to_gcp

on:
  #schedule:
  #  - cron: '0 */6 * * *' # Run every six hours
  workflow_dispatch:
#  push:
#    branches: main

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::googleCloudStorageR
            any::stringr

      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Push to GCP
        uses: 'google-github-actions/auth@v2'
        with:
            GCS_AUTH_FILE: '${{ secrets.GOOGLE_CREDENTIALS }}' 
        run: Rscript -e 'source("250127-SnowfallPolygons_season.R")'