name: push_to_gcp

on:
  #schedule:
  #  - cron: '0 */6 * * *' # Run every six hours
  workflow_dispatch:
#  push:
#    branches: main

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::googleCloudStorageR
            any::stringr

      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Save GCP credentials to temp file
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > gcp-key.json

      - name: Run R script
        env:
          GCS_AUTH_FILE: gcp-key.json
        run: Rscript -e 'source("251128-PushToGCP.R")'