name: Upload to GCP

on:
  repository_dispatch:
    types: [trigger-push-to-gcp]
  workflow_dispatch:
  #push:
  #  branches:
  #    - main  # Trigger on pushes to the main branch
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-storage

      - name: Decode GCP credentials
        env:
          GCP_STORAGE_KEY_BASE64: ${{ secrets.GCP_STORAGE_KEY_BASE64 }}
        run: |
          echo "${GCP_STORAGE_KEY_BASE64}" | base64 --decode > storage-key.json

      - name: Run script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/storage-key.json
        run: python upload_to_gcp.py
