name: Python-Scrape recent snowfall

on:
  #repository_dispatch:
  #  types: [trigger-push-to-gcp]
  workflow_dispatch:
  #push:
  #  branches:
  #    - main  # Trigger on pushes to the main branch
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y gdal-bin=3.7.2.* libgdal-dev

      - name: Verify GDAL Installation
        run: |
          gdalinfo --version
          python3 -c "import sys; print(sys.path)"
          #python3 -c "from osgeo import gdal; print(gdal.VersionInfo())"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          #pip install pygdal=="$(gdal-config --version).*"
          pip install pygdal==3.7.2.*
          pip install -r requirements.txt

      - name: Run script
        run: python PolygonizeRaster.py
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -m "Latest data: $(date)" || exit 0
          git push 
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions