name: Remove overlaps v2

on:
  repository_dispatch:
    types: [trigger-overlaps-removal-v2]
  workflow_dispatch:
  #push:
  #  branches:
  #    - main  # Trigger on pushes to the main branch
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Node.js #for Mapshaper
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set the version of Node.js

      - name: Install Mapshaper
        run: npm install -g mapshaper  # Install Mapshaper globally
      
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y gdal-bin libgdal-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements2.txt
          #pip install osgeo  # Sometimes needed separately
          
      - name: Remove overlaps from day timeframes
        run: python RemoveOverlaps.py
        
      - name: Create hexagon tessalation and compress season map
        run: python CleanSeason.py
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -m "Latest data: $(date)" || exit 0
          git push 
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
          
      - name: Trigger push to Google Cloud
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-push-to-gcp
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'