name: Scrape 'n Clean

on:
  repository_dispatch:
    types: [trigger-scrape-n-clean]
  #schedule:
  #  - cron: '0 */6 * * *' # Run every six hours
  workflow_dispatch:
#  push:
#    branches: main

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::terra
            any::sf
            any::dplyr 
            any::stringr
            any::tesseract
            any::lubridate 
            any::geojsonio
            any::tibble
            any::jsonlite
            any::stars
            any::smoothr
 
       #Added to try caching to save time.      
      - name: Cache R packages
        uses: actions/cache@v4 #changed from 2>4 because 2 is being phased out.
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
            
      - name: Scrape latest snowfall season accumulation data
        run: Rscript -e 'source("250130-SnowfallPolygons_season.R")'
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -m "Latest data: $(date)" || exit 0
          git push 
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions

      - name: Set up Node.js #for Mapshaper
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set the version of Node.js

      - name: Install Mapshaper
        run: npm install -g mapshaper  # Install Mapshaper globally

      - name: Run Mapshaper-season
        run: mapshaper outputs/season/season_inches_snow_accumulation_latest_full.json -o precision=0.1 outputs/season/season_inches_snow_accumulation_latest.json  # Run your Mapshaper command directly

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -m "Latest data: $(date)" || exit 0
          git push 
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
          
      - name: Run smoothr on day timeframes and compress season
        #run: Rscript -e 'source("250130-FixSeason.R")' #run all four timeframes
        run: Rscript -e 'source("250131-CleanPolygons.R")' 
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -m "Latest data: $(date)" || exit 0
          git push 
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
          
      - name: Trigger Overlaps removal
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-overlaps-removal
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'